# ECEN 489-500: Python Programming Exercise 1
Author: Brandon Thayer


## Imports

In [4]:
import numpy as np

print('Imports complete.')

Imports complete.


## Initialization

In [8]:
# Example world from the exercise prompt.
world = [
    [0, 1, 1, 1, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 1, 1],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0]]

# Put the world in a numpy array.
w = np.array(world)

# Initialize expansion array.
# TODO: This will certainly change.
e = np.zeros_like(w) - 1

# Initialize path array.
p = w.astype(np.chararray)

print('Initialization complete.')
print('World: ')
print(w)
print('Expansion array: ')
print(e)
print('Path array: ')
print(p)

Initialization complete.
World: 
[[0 1 1 1 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 1 0 1 1]
 [0 0 0 1 0 0 0]
 [0 0 1 1 0 0 0]]
Expansion array: 
[[-1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1]]
Path array: 
[[0 1 1 1 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 1 0 1 1]
 [0 0 0 1 0 0 0]
 [0 0 1 1 0 0 0]]


## Functions

In [28]:
def _check_move(world, position, previous_position):
    """Helper function to check if a move is valid.
    
    For information on inputs, check get_available_moves function.
    """
    # No going backward.
    if position == previous_position:
        return False
    
    # Our world doesn't wrap, so no negative indices allowed.
    if (position[0] < 0) or (position[1] < 0):
        return False
    
    # Check the value of the position in the world
    try:
        position_value = world[position[0]][position[1]]
    except IndexError:
        # The position is out of bounds.
        return False
    
    # The position is valid if the value is 0, but not if it's a 1.
    if position_value == 1:
        return False
    elif position_value == 0:
        return True
    else:
        raise ValueError('position_value evaluated to {}'.format(position_value))
    

def get_available_moves(world, position, previous_position):
    """Determine the set of all viable next moves.
    
    :param world: numpy array containing the world. 0 is a valid location to occupy, 1 is not.
    :param position: two element tuple indicating current position in the world.
    :param previous_position: two element tuple indicating previous position in the world.
    """
    # Initialize array to hold possible moves. None will indicate the move is not valid.
    # ORDER: North, East, South, West
    moves = [None,] * 4
    
    # North: Subtract 1 from the row index.
    north = (position[0] - 1, position[1])
    if _check_move(world, north, previous_position):
        moves[0] = north
        
    # East: Add 1 to the column index.
    east = (position[0], position[1] + 1)
    if _check_move(world, east, previous_position):
        moves[1] = east
        
    # South: Add 1 to the row index.
    south = (position[0] + 1, position[1])
    if _check_move(world, south, previous_position):
        moves[2] = south
        
    # West: Subtract 1 from the column index.
    west = (position[0], position[1] - 1)
    if _check_move(world, west, previous_position):
        moves[3] = west
        
    return moves

In [29]:
moves = get_available_moves(world=w, position=(0, 0), previous_position=None)
print(moves)

[None, None, (1, 0), None]


In [18]:
(1, 1) == None

False